spring.application.name=backend-r

# DATABASE CONNECTIVITY
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=Asia/Manila&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Secrets
server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET:your_super_secret_key_for_jwt_token_12345678901234567890}
# your_super_secret_key_for_jwt_token_12345678901234567890

app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
# 86400000

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

